onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - aws-sdk
  - bcrypt
  - cpu-features
  - esbuild
  - node-pty
  - prisma
  - protobufjs
  - sharp
  - ssh2
