// FilePath: src/modules/planner/dto/create-planner.dto.ts
// Title: DTOs for creating a planner request with file changes (with diff support)
// Reason: Add `diff` property to allow unified-diff style patches in file change requests.

import {
  IsString,
  IsArray,
  ValidateNested,
  IsEnum,
  IsOptional,
  IsDefined,
} from 'class-validator';
import { Type } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { FileAction } from '@prisma/client';

export class FileChangeDto {
  @ApiProperty({
    description: 'Absolute or relative path of the file to be changed.',
    example: 'src/components/WelcomeMessage.tsx',
  })
  @IsString()
  @IsDefined()
  filePath: string;

  @ApiProperty({
    enum: FileAction,
    description: 'Type of operation to perform on the file.',
    example: FileAction.ADD,
  })
  @IsEnum(FileAction)
  @IsDefined()
  action: FileAction;

  @ApiPropertyOptional({
    description:
      'Optional unified diff to apply instead of providing full newContent.',
    example: '--- a/src/old.ts\n+++ b/src/old.ts\n@@ ...',
  })
  @IsString()
  @IsOptional()
  diff?: string;

  @ApiPropertyOptional({
    description:
      'New content for ADD, MODIFY, or REPAIR operations when diff is not provided.',
    example:
      'import React from "react";\n\nconst WelcomeMessage = () => <div>Hello, AI User!</div>;\n\nexport default WelcomeMessage;',
  })
  @IsString()
  @IsOptional()
  newContent?: string;

  @ApiPropertyOptional({
    description: 'Brief explanation or justification for this file change.',
    example: 'New component to display a welcome message.',
  })
  @IsString()
  @IsOptional()
  reason?: string;
}

export class CreatePlannerDto {
  @ApiProperty({
    description: 'High-level title for the overall changes or response.',
    example: 'Implement User Authentication Module',
  })
  @IsString()
  @IsDefined()
  title: string;

  @ApiProperty({
    description: 'Concise summary describing the overall changes or solution.',
    example:
      'Implemented a new React component `WelcomeMessage.tsx` to display a greeting message.',
  })
  @IsString()
  @IsDefined()
  summary: string;

  @ApiPropertyOptional({
    description: 'Detailed reasoning behind the proposed changes.',
    example:
      'The user requested a React component, so I created a functional component in TypeScript and placed it in `src/components`.',
  })
  @IsString()
  @IsOptional()
  thoughtProcess?: string;

  @ApiProperty({
    type: [FileChangeDto],
    description: 'List of proposed file changes generated by the LLM.',
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => FileChangeDto)
  @IsDefined()
  changes: FileChangeDto[];
}
