/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NonEmptyString = string;
export type Semver = string;
export type Url = string;
export type FileChange = {
  [k: string]: unknown;
} & {
  filePath: string;
  action: 'add' | 'modify' | 'delete' | 'repair' | 'analyze';
  newContent?: string;
  reason?: string;
  encoding?: 'utf-8' | 'base64';
  /**
   * SHA256 hex of newContent (if provided)
   */
  checksum?: string;
  sizeBytes?: number;
};

/**
 * Production-ready schema describing outputs of an LLM-driven Code/Application Generation Builder. Contains project metadata, generation parameters, modules, artifacts, provenance, and CI/security information.
 */
export interface LLMCodeApplicationGenerationBuilderModelProduction {
  title: NonEmptyString;
  summary: string;
  thoughtProcess: string;
  /**
   * Extended Markdown docs (optional)
   */
  documentation?: string;
  projectMetadata: {
    name: NonEmptyString;
    version: Semver;
    language: string;
    /**
     * @minItems 1
     */
    frameworks: [string, ...string[]];
    /**
     * e.g., npm, yarn, pnpm, pip
     */
    packageManager?: string;
    license?: string;
    authors?: string[];
    repository?: Url;
    createdAt: string;
    lastUpdated?: string;
    ciConfigured?: boolean;
  };
  generationParameters: {
    model: string;
    temperature: number;
    maxTokens: number;
    prompt?: string;
    seed?: number;
    stopSequences?: string[];
    metadata?: {
      [k: string]: unknown;
    };
  };
  /**
   * @minItems 1
   */
  modules: [
    {
      name: string;
      description: string;
      dependencies: Dependency[];
      apiEndpoints?: ApiEndpoint[];
      tests?: {
        unitTests?: boolean;
        integrationTests?: boolean;
        coveragePercent?: number;
      };
      linting?: {
        tool?: string;
        configured?: boolean;
      };
    },
    ...{
      name: string;
      description: string;
      dependencies: Dependency[];
      apiEndpoints?: ApiEndpoint[];
      tests?: {
        unitTests?: boolean;
        integrationTests?: boolean;
        coveragePercent?: number;
      };
      linting?: {
        tool?: string;
        configured?: boolean;
      };
    }[],
  ];
  buildScripts?: {
    [k: string]: string;
  };
  changes: FileChange[];
  artifacts: Artifact[];
  provenance: {
    /**
     * Agent (LLM/model/version) or tool name
     */
    generatedBy: string;
    generatedAt: string;
    promptRef?: string;
    commitHash?: string;
    generationId?: string;
    humanReview?: {
      required?: boolean;
      reviewer?: string;
      reviewedAt?: string;
      notes?: string;
    };
    signatures?: {
      keyId: string;
      signature: string;
      algorithm: string;
      signedAt?: string;
    }[];
  };
  ci?: {
    provider?: string;
    pipelineRef?: string;
    status?: 'not-configured' | 'passing' | 'failing' | 'unknown';
    requiredChecks?: string[];
  };
  containerization?: {
    dockerfilePath?: string;
    imageName?: string;
    baseImage?: string;
    recommendedRuntime?: string;
  };
  security?: {
    /**
     * Path to SBOM artifact
     */
    sbom?: string;
    securityScans?: SecurityScan[];
    licenseCompliance?: {
      status?: 'ok' | 'warning' | 'violation' | 'unknown';
      details?: string;
    };
    /**
     * high-level note: e.g., 'no secrets persisted; use vault for runtime secrets'.
     */
    secretsHandling?: string;
  };
  gitInstructions?: string[];
}
export interface Dependency {
  name: NonEmptyString;
  version?: Semver;
  source?: Url;
  dev?: boolean;
}
export interface ApiEndpoint {
  path: string;
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS' | 'HEAD';
  description?: string;
  authRequired?: boolean;
  requestSchemaRef?: string;
  responseSchemaRef?: string;
}
export interface Artifact {
  type:
    | 'docker-image'
    | 'archive'
    | 'binary'
    | 'sbom'
    | 'report'
    | 'container-image';
  /**
   * relative or registry path
   */
  path: string;
  sha256?: string;
  sizeBytes?: number;
  platform?: string;
  metadata?: {
    [k: string]: unknown;
  };
}
export interface SecurityScan {
  tool?: string;
  date?: string;
  summary?: string;
  critical?: number;
  high?: number;
  medium?: number;
  low?: number;
  detailsRef?: string;
}
